name: Docker Image CI

env:
  VERSION:

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.6.0
        with:
          cosign-release: "v2.2.4"

      - name: Extract Tag from Dockerfile
        id: read-version
        run: |
          TAG=$(grep -m 1 '^FROM pihole/pihole:' Dockerfile | cut -d ':' -f 2)
          echo "VERSION=${TAG}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry (GHCR)
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./pihole-unbound
          file: ./Dockerfile
          push: true
          build-args: VERSION=${{ env.VERSION }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          tags: |
            ${{ github.repository_owner }}/pihole-unbound:${{ env.VERSION }} 
            ${{ github.repository_owner }}/pihole-unbound:latest
            ghcr.io/${{ github.repository_owner }}/pihole-unbound:${{ env.VERSION }} 
            ghcr.io/${{ github.repository_owner }}/pihole-unbound:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image
        env:
          TAGS: "${{ env.VERSION }},latest"
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          make_latest: true
          body: |
            Updated PiHole image to ${{ env.VERSION }}, for a full list of changelogs please refer to [this link](https://github.com/pi-hole/docker-pi-hole/releases/tag/${{ env.VERSION }})
          token: ${{ secrets.GITHUB_TOKEN }}
