name: Update PiHole Version

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update-version-tag:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Read current repository version
        id: read-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./VERSION

      - name: Get latest pihole tag
        id: get-latest-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: pi-hole/docker-pi-hole
          releases-only: true

      - name: Compare tags
        if: steps.read-version.outputs.content != steps.get-latest-tag.outputs.tag
        uses: DamianReeves/write-file-action@master
        with:
          path: ./VERSION
          write-mode: overwrite
          contents: ${{ steps.get-latest-tag.outputs.tag }}

      - name: Commit & Push
        if: steps.read-version.outputs.content != steps.get-latest-tag.outputs.tag
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ steps.get-latest-tag.outputs.tag }}
